
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.10.123:1521/orcl
    username: c##kminer
    password: kminerpass
    type: org.springframework.jdbc.datasource.SingleConnectionDataSource

  rabbitmq:
    host: 192.168.10.233
    port: 5672
    username: admin
    password: admin

  application:
    name: oracle-mining

mining:
  #多租户模式 设置true 普通模式设置 false
  multiTenant: true
  maxTransitionMinutes: 10
  initStartTime: NULL

  #同步表名， 竖线后面为推送条件,可以为空,条件为true时不推送.  条件为js语法  字段名变量为大写
  tables:
    - CIICFS_WAGE_TEST.A001|A001755 == '00900'
    - CIICFS_WAGE_TEST.A002
    - CIICFS.B001

#  sync-table: ciicfs_test.FS_WAGE_ITEM_CW,ciicfs.b001
  interval: 5

  exchangeName: oracle-sync.exchange
  queueName: oracle-sync.ciic-bsp-cus,oracle-sync.ciic-bsp-biz

