
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.10.20:1521/orcl
    username: kminer
    password: kminerpass

mining:
  init-start-scn: 0
  sync-table: ciicfs_test.*,ciicfs.b001
  polling-interval: 5
  polling-size: 1000
