server:
  port: 8484

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.10.123:1521/orcl
    username: c##kminer
    password: kminerpass
    type: org.springframework.jdbc.datasource.SingleConnectionDataSource

  rabbitmq:
    host: 192.168.251.61
    port: 5672
    username: admin
    password: admin

  application:
    name: oracle-mining

  redis:
    host: 127.0.0.1
    port: 6379


mining:
  #多租户模式 设置true 普通模式设置 false
  multiTenant: true
  logFileScaned: 3


  #同步表名， 竖线后面为推送条件,可以为空,条件为true时不推送.  条件为js语法  字段名变量为大写
  tables:
    - CIICFS_TEST.E001
    - CIICFS_TEST.E200
    - CIICFS_TEST.E201
    - CIICFS_TEST.F001
    - CIICFS_TEST.F203
    - CIICFS_TEST.F204
    - CIICFS_TEST.E204
    - CIICFS_TEST.E204_TAXHISTORY
    - CIICFS_TEST.F200
    - CIICFS_TEST.F201
    - CIICFS_WAGE_TEST.A001
    - CIICFS_WAGE_TEST.A002
    - CIICFS_WAGE_TEST.A200
    - CIICFS_WAGE_TEST.A282
    - CIICFS_WAGE_TEST.A815
    - CIICFS_WAGE_TEST.A703
    - CIICFS_WAGE_TEST.B001
    - CIICFS_WAGE_TEST.B200
    - CIICFS_WAGE_TEST.B201
    - CIICFC_HRCLOUD_20200902.A001
    - CIICFC_HRCLOUD_20200902.A003
    - CIICFC_HRCLOUD_20200902.A012
    - CIICFC_HRCLOUD_20200902.A019
    - CIICFC_HRCLOUD_20200902.A026
    - CIICFC_HRCLOUD_20200902.CUSTOM_INFO


  #  sync-table: ciicfs_test.FS_WAGE_ITEM_CW,ciicfs.b001

  exchangeName: oracle-sync.exchange
  queueName: oracle-sync.ciic-bsp-cus,oracle-sync.ciic-bsp-biz,oracle-sync.ciic-bsp-wage

